Repository colcon/colcon-mixin-repository, pull requests merged in 2018-09, with the labels that each got.

#1 add Travis configuration
  .travis.yml
Labels: enhancement

#5 fix root key in index
  index.yaml
Labels: bug, review

#3 add mixins to choose the CMake build type
  build-type.mixin
  index.yaml
Labels: enhancement, review

#2 add mixins to toggle the CMake BUILD_TESTING flag
  build-testing.mixin
  index.yaml
Labels: enhancement, review

#4 add mixins to test only linter tests or non-linter tests
  index.yaml
  test-linters.mixin
Labels: enhancement, review

#9 relax line length check
  lint.py
Labels: review

#11 Remove non-standard `-DCOVERAGE_RUN=1`
  coverage.mixin
Labels: review
